# Generated by Django 5.0.6 on 2026-01-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicscore',
            name='difficulty',
            field=models.CharField(default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='logicscore',
            name='player_name',
            field=models.CharField(default='Anonym', max_length=100),
        ),
    ]
