# Generated by Django 5.0.6 on 2025-12-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameState',
        ),
    ]
